In [1]:
import warnings
import importlib
import sys

import pandas as pd
import torch
from transformers import AutoTokenizer, BigBirdConfig, BigBirdForMaskedLM
import tqdm

from CodonTransformer.CodonJupyter import (
    UserContainer,
    display_protein_input,
    format_model_output,
)
from CodonTransformer.CodonPrediction import predict_dna_sequence

warnings.filterwarnings("ignore")

# Reload modules to get latest changes
if 'CodonTransformer.CodonJupyter' in sys.modules:
    importlib.reload(sys.modules['CodonTransformer.CodonJupyter'])
    from CodonTransformer.CodonJupyter import format_model_output

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [8]:
# Load model and tokenizer
tokenizer = AutoTokenizer.from_pretrained("adibvafa/CodonTransformer")
model = BigBirdForMaskedLM.from_pretrained("gupta-reyansh123/Rice_Optimizer")

Loading weights:   0%|          | 0/204 [00:00<?, ?it/s]

**Optimizing a Single Sequence**
-------------------------------------
1. Run the next code cell and input your DNA sequence and select an organism

2. Run the code cell after it to optimize the sequence and display it.

DNA sequences should only contain valid nucleotides (A, T, G, C) and will be automatically converted to a protein sequence for optimization.

In [6]:
user = UserContainer()
user.organism = 0  # Set to organism 0
display_protein_input(user)

VBox(children=(HTML(value='<b style="font-size:20px;">Enter Protein Sequence:</b><div style="height:18px;"></d…

HTML(value='\n        <style>\n            .widget-textarea > textarea {\n                font-size: 12px;\n  …

In [10]:
output = predict_dna_sequence(
    protein=user.protein,
    organism=user.organism,
    device=DEVICE,
    tokenizer=tokenizer,
    model=model,
    attention_type="original_full",
    deterministic=True,
)

print(format_model_output(output))

-----------------------------
|       Predicted DNA       |
-----------------------------
ATGGCTTTGTGGGCTCGACCTTAA

**Optimizing Multiple Sequences**
-------------------------------------
1. Create a CSV file that has columns 'protein_sequence' and 'organism'.
   You can have other columns in any order.

2. Replace the _dataset_path_ below with the actual path to your CSV file.

3. Run the next code cells to optimize and save the predicted DNA sequences.

In [ ]:
# Update with the actual path to your dataset
dataset_path = "ModelTest/test_data.csv"
output_path = "ModelTest/model_predictions.csv"

dataset = pd.read_csv(dataset_path, index_col=0)
dataset["predicted_dna"] = None
dataset.head()

,id,description,sequence,protein,codons,length,GC,GC3,Original CAI,tAI,predicted_dna
4392,NZ_JAFLWW010000007.1_121,NZ_JAFLWW010000007.1_121 # 134707 # 135600 # 1...,ATGTCAGGTCTGCGTCAGATCGCATTCTACGGAAAGGGAGGCATCG...,MSGLRQIAFYGKGGIGKSTTSQNTLAALVDLGQKILIVGCDPKADS...,"['ATG', 'TCA', 'GGT', 'CTG', 'CGT', 'CAG', 'AT...",894,0.604027,0.825503,0.875295,0.3357,None
1653,JACRLO010000018.1_2,JACRLO010000018.1_2 # 515 # 1354 # -1 # ID=12_...,ATGAGACAGATTGCAATCTACGGCAAGGGCGGCATCGGCAAGTCAA...,MRQIAIYGKGGIGKSTTTQNLVAALAEAGRKCMIIGCDPKADSTRL...,"['ATG', 'AGA', 'CAG', 'ATT', 'GCA', 'ATC', 'TA...",840,0.550000,0.678571,0.829446,0.2896,None
2981,CAIYDK010000047.1_28,CAIYDK010000047.1_28 # 19349 # 20233 # 1 # ID=...,ATGGCTAAACTTCGGCAAATCGCCTTCTATGGCAAGGGTGGGATCG...,MAKLRQIAFYGKGGIGKSTTSQNTLAALSDLGQKILIVGCDPKADS...,"['ATG', 'GCT', 'AAA', 'CTT', 'CGG', 'CAA', 'AT...",885,0.579661,0.755932,0.844710,0.3156,None
23,PQXF01000008.1_109,PQXF01000008.1_109 # 76242 # 77072 # -1 # ID=1...,ATGTTTGCTGTGATAAGGCAGCGCTTGAGAACGATGTACCGAACAA...,MFAVIRQRLRTMYRTRRIAIYGKGGIGKSSTASNVAAACADAGYSV...,"['ATG', 'TTT', 'GCT', 'GTG', 'ATA', 'AGG', 'CA...",831,0.535499,0.613718,0.782881,0.2764,None
1850,JAFWUY010000122.1_9,JAFWUY010000122.1_9 # 8206 # 9057 # 1 # ID=84_...,ATGCCGAAGTACAGACAGATCGCCATCTACGGAAAAGGTGGCATCG...,MPKYRQIAIYGKGGIGKSTTTQNLTAGLAERGKKVMVVGCDPKADS...,"['ATG', 'CCG', 'AAG', 'TAC', 'AGA', 'CAG', 'AT...",852,0.490610,0.521127,0.749842,0.2167,None

In [30]:
# Update with the actual path to your dataset
dataset_path = "ModelTest/test_data.csv"
output_path = "ModelTest/model_predictions.csv"

dataset = pd.read_csv(dataset_path, index_col=0)
dataset["predicted_dna"] = None
dataset.head()

,id,description,sequence,protein,codons,length,GC,GC3,Original CAI,tAI,predicted_dna
4392,NZ_JAFLWW010000007.1_121,NZ_JAFLWW010000007.1_121 # 134707 # 135600 # 1...,ATGTCAGGTCTGCGTCAGATCGCATTCTACGGAAAGGGAGGCATCG...,MSGLRQIAFYGKGGIGKSTTSQNTLAALVDLGQKILIVGCDPKADS...,"['ATG', 'TCA', 'GGT', 'CTG', 'CGT', 'CAG', 'AT...",894,0.604027,0.825503,0.875295,0.3357,None
1653,JACRLO010000018.1_2,JACRLO010000018.1_2 # 515 # 1354 # -1 # ID=12_...,ATGAGACAGATTGCAATCTACGGCAAGGGCGGCATCGGCAAGTCAA...,MRQIAIYGKGGIGKSTTTQNLVAALAEAGRKCMIIGCDPKADSTRL...,"['ATG', 'AGA', 'CAG', 'ATT', 'GCA', 'ATC', 'TA...",840,0.550000,0.678571,0.829446,0.2896,None
2981,CAIYDK010000047.1_28,CAIYDK010000047.1_28 # 19349 # 20233 # 1 # ID=...,ATGGCTAAACTTCGGCAAATCGCCTTCTATGGCAAGGGTGGGATCG...,MAKLRQIAFYGKGGIGKSTTSQNTLAALSDLGQKILIVGCDPKADS...,"['ATG', 'GCT', 'AAA', 'CTT', 'CGG', 'CAA', 'AT...",885,0.579661,0.755932,0.844710,0.3156,None
23,PQXF01000008.1_109,PQXF01000008.1_109 # 76242 # 77072 # -1 # ID=1...,ATGTTTGCTGTGATAAGGCAGCGCTTGAGAACGATGTACCGAACAA...,MFAVIRQRLRTMYRTRRIAIYGKGGIGKSSTASNVAAACADAGYSV...,"['ATG', 'TTT', 'GCT', 'GTG', 'ATA', 'AGG', 'CA...",831,0.535499,0.613718,0.782881,0.2764,None
1850,JAFWUY010000122.1_9,JAFWUY010000122.1_9 # 8206 # 9057 # 1 # ID=84_...,ATGCCGAAGTACAGACAGATCGCCATCTACGGAAAAGGTGGCATCG...,MPKYRQIAIYGKGGIGKSTTTQNLTAGLAERGKKVMVVGCDPKADS...,"['ATG', 'CCG', 'AAG', 'TAC', 'AGA', 'CAG', 'AT...",852,0.490610,0.521127,0.749842,0.2167,None

In [31]:
for index, data in tqdm.tqdm(
    dataset.iterrows(),
    desc=f"CodonTransformer Predicting",
    unit=" Sequences",
    total=dataset.shape[0],
):

    outputs = predict_dna_sequence(
        protein=data["protein"],
        organism=0,
        device=DEVICE, 
        tokenizer=tokenizer,
        model=model,
    )
    dataset.loc[index, "predicted_dna"] = outputs.predicted_dna

dataset.to_csv(output_path)
dataset.head()

CodonTransformer Predicting: 100%|██████████| 100/100 [00:49<00:00,  2.01 Sequences/s]

,id,description,sequence,protein,codons,length,GC,GC3,Original CAI,tAI,predicted_dna
4392,NZ_JAFLWW010000007.1_121,NZ_JAFLWW010000007.1_121 # 134707 # 135600 # 1...,ATGTCAGGTCTGCGTCAGATCGCATTCTACGGAAAGGGAGGCATCG...,MSGLRQIAFYGKGGIGKSTTSQNTLAALVDLGQKILIVGCDPKADS...,"['ATG', 'TCA', 'GGT', 'CTG', 'CGT', 'CAG', 'AT...",894,0.604027,0.825503,0.875295,0.3357,ATGTCTGGTCTTCGACAAATCGCTTTCTATGGCAAGGGCGGCATCG...
1653,JACRLO010000018.1_2,JACRLO010000018.1_2 # 515 # 1354 # -1 # ID=12_...,ATGAGACAGATTGCAATCTACGGCAAGGGCGGCATCGGCAAGTCAA...,MRQIAIYGKGGIGKSTTTQNLVAALAEAGRKCMIIGCDPKADSTRL...,"['ATG', 'AGA', 'CAG', 'ATT', 'GCA', 'ATC', 'TA...",840,0.550000,0.678571,0.829446,0.2896,ATGCGACAAATTGCTATCTACGGCAAGGGCGGCATCGGCAAGAGCA...
2981,CAIYDK010000047.1_28,CAIYDK010000047.1_28 # 19349 # 20233 # 1 # ID=...,ATGGCTAAACTTCGGCAAATCGCCTTCTATGGCAAGGGTGGGATCG...,MAKLRQIAFYGKGGIGKSTTSQNTLAALSDLGQKILIVGCDPKADS...,"['ATG', 'GCT', 'AAA', 'CTT', 'CGG', 'CAA', 'AT...",885,0.579661,0.755932,0.844710,0.3156,ATGGCTAAGCTTCGACAAATCGCTTTCTATGGCAAGGGCGGCATCG...
23,PQXF01000008.1_109,PQXF01000008.1_109 # 76242 # 77072 # -1 # ID=1...,ATGTTTGCTGTGATAAGGCAGCGCTTGAGAACGATGTACCGAACAA...,MFAVIRQRLRTMYRTRRIAIYGKGGIGKSSTASNVAAACADAGYSV...,"['ATG', 'TTT', 'GCT', 'GTG', 'ATA', 'AGG', 'CA...",831,0.535499,0.613718,0.782881,0.2764,ATGTTTGCTGTTATCCGACAACGACTTCGAACAATGTACAGGACCC...
1850,JAFWUY010000122.1_9,JAFWUY010000122.1_9 # 8206 # 9057 # 1 # ID=84_...,ATGCCGAAGTACAGACAGATCGCCATCTACGGAAAAGGTGGCATCG...,MPKYRQIAIYGKGGIGKSTTTQNLTAGLAERGKKVMVVGCDPKADS...,"['ATG', 'CCG', 'AAG', 'TAC', 'AGA', 'CAG', 'AT...",852,0.490610,0.521127,0.749842,0.2167,ATGCCTAAGTATCGACAAATCGCTATCTATGGCAAGGGCGGCATCG...